before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libdbus-1-dev ; fi

language: rust

rust:
  - nightly

os:
  - linux
  - osx

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
