[package]
name = "tiny"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]

[lib]
name = "tiny"
path = "src/lib.rs"

[[bin]]
name = "tiny"
path = "bin/main.rs"

[dependencies]
libc = "0.2.8"
net2 = "0.2.23"
rand = "0.3.14"
rustbox = { git = "https://github.com/gchp/rustbox.git" }
termbox-sys = "0.2.9"
time = "0.1"
