[package]
name = "tiny"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
repository = "https://github.com/osa1/tiny"
readme = "README.md"
license = "MIT"
keywords = ["irc"]
categories = ["network-programming"]

[workspace]

[lib]
name = "tiny"
path = "src/lib.rs"

[[bin]]
name = "tiny"
path = "bin/main.rs"

[dependencies]
ev_loop = { path = "ev_loop/" }
libc = "0.2.22"
net2 = "0.2.23"
term_input = { path = "term_input/" }
termbox_simple = { path = "termbox/" }
time = "0.1"
yaml-rust = { git = "https://github.com/chyh1990/yaml-rust.git" }
