[package]
name = "termbox_simple"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
links = "termbox_simple"
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
gcc = "0.3.35"
