name: CI

on: [push, pull_request]

jobs:
  Linux_default:
    name: '[Linux, default] Build and test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install native dependencies
        run: sudo apt-get install libdbus-1-dev pkg-config libssl-dev

      - name: Get nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rustfmt
            override: true

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --all --verbose

      - name: Check formatting
        run: cargo fmt --all -- --check

  Linux_rustls:
    name: '[Linux, rustls] Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install native dependencies
        run: sudo apt-get install libdbus-1-dev

      - name: Get nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rustfmt
            override: true

      - name: Build with rustls
        run: cd tiny && cargo build --verbose --no-default-features --features tls-rustls

  OSX:
    name: '[OSX, default] Build and test'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rustfmt
            override: true

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Check formatting
        run: cargo fmt --all -- --check

  OSX_rustls:
    name: '[OSX, rustls] Build'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rustfmt
            override: true

      - name: Build
        run: cd tiny && cargo build --verbose --no-default-features --features tls-rustls
